/**
 * Self-hosts the hub's webfonts, Geist and Geist Mono.
 *
 * The hub used to load them from Google Fonts. That stylesheet request sends
 * every visitor's address to Google LLC on every visit, before the consent bar
 * is answered and after a refusal, while the shared policy
 * (devslab.kr/privacy, which covers this site) says nothing reaches Google
 * until analytics is granted. devslab.kr self-hosts the same two fonts.
 *
 *   1. copies the upright variable woff2 files that @fontsource-variable/geist
 *      and @fontsource-variable/geist-mono declare in their wght.css (every
 *      subset; unicode-range means a browser downloads only the subsets the
 *      text on the page uses) into assets/fonts/, with each family's licence;
 *   2. writes assets/fonts/fonts.css from those wght.css files, under the
 *      family names the page's CSS asks for ('Geist', 'Geist Mono').
 *
 * assets/fonts/ holds nothing else. `--check` changes nothing and fails if any
 * file there is stale, missing or extra (npm test runs it).
 */
import { mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));
const out = join(root, 'assets/fonts');
const check = process.argv.includes('--check');

const FAMILIES = [
  { pkg: '@fontsource-variable/geist', from: 'Geist Variable', family: 'Geist', licence: 'OFL-geist.txt' },
  { pkg: '@fontsource-variable/geist-mono', from: 'Geist Mono Variable', family: 'Geist Mono', licence: 'OFL-geist-mono.txt' },
];

const expected = new Map(); // file name in assets/fonts → Buffer
const sources = [];
const css = [];
for (const { pkg, from, family, licence } of FAMILIES) {
  const dir = dirname(fileURLToPath(import.meta.resolve(`${pkg}/package.json`)));
  const { version } = JSON.parse(readFileSync(join(dir, 'package.json'), 'utf8'));
  sources.push(`${pkg}@${version}`);
  const sheet = readFileSync(join(dir, 'wght.css'), 'utf8').replaceAll('\r\n', '\n');
  const faces = sheet.match(/\/\*[^*]*\*\/\n@font-face \{[^}]*\}/g) ?? [];
  if (faces.length === 0) throw new Error(`${pkg}/wght.css has no @font-face rules`);
  for (const face of faces) {
    if (!face.includes(`font-family: '${from}';`)) throw new Error(`${pkg}: a face is not '${from}':\n${face}`);
    if (!face.includes('font-style: normal;')) throw new Error(`${pkg}: wght.css is no longer upright only:\n${face}`);
    const files = [...face.matchAll(/url\(\.\/files\/([a-z0-9-]+\.woff2)\)/g)].map((m) => m[1]);
    if (files.length !== 1) throw new Error(`${pkg}: expected one woff2 per face:\n${face}`);
    expected.set(files[0], readFileSync(join(dir, 'files', files[0])));
    css.push(face.replace(`font-family: '${from}';`, `font-family: '${family}';`).replace(`url(./files/${files[0]})`, `url(./${files[0]})`));
  }
  expected.set(licence, readFileSync(join(dir, 'LICENSE')));
}
const header =
  `/* Generated by scripts/sync-fonts.mjs from ${sources.join(' and ')} — do not edit.\n` +
  ` * Self-hosted so no page asks Google Fonts for anything.\n` +
  ` * SIL Open Font License 1.1: ${FAMILIES.map((f) => f.licence).join(', ')}. */\n\n`;
expected.set('fonts.css', Buffer.from(header + css.join('\n\n') + '\n'));

const stale = [];
mkdirSync(out, { recursive: true });
const sameBytes = (name, current, next) =>
  name.endsWith('.woff2') ? current.equals(next) : current.toString('utf8').replaceAll('\r\n', '\n') === next.toString('utf8').replaceAll('\r\n', '\n');
for (const [name, next] of expected) {
  const path = join(out, name);
  let current = null;
  try {
    current = readFileSync(path);
  } catch {
    // a new file
  }
  if (current !== null && sameBytes(name, current, next)) continue;
  if (check) stale.push(relative(root, path).replaceAll('\\', '/'));
  else writeFileSync(path, next);
}
for (const name of readdirSync(out)) {
  if (expected.has(name)) continue;
  if (check) stale.push(`assets/fonts/${name} (not generated)`);
  else rmSync(join(out, name), { recursive: true });
}

if (stale.length) {
  console.error(`Font files are stale — run npm run sync:fonts:\n  ${stale.join('\n  ')}`);
  process.exit(1);
}
console.log(check ? 'font files are current' : `fonts synced (${sources.join(', ')}): ${[...expected.keys()].join(', ')}`);
